Homework 3
made-ml-in-prod-2021/imdxd pull request #4
Opened 2021-06-08 12:30 UTC by IMDxD

0) Поднимите airflow локально, используя docker compose - Сделано
1) (5 баллов) Реализуйте dag, который генерирует данные для обучения модели - upload.py dag
2) (10 баллов) Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день. В вашем пайплайне должно быть как минимум 4 стадии, но дайте волю своей фантазии=) - train.py dag
3) Реализуйте dag, который использует модель ежедневно (5 баллов) - predict.py dag
3а)  Реализуйте сенсоры на то, что данные готовы для дагов тренировки и обучения (3 доп балла) - добавлены сенсоры на данные и модель
4) все даги реализованы только с помощью DockerOperator (10 баллов) - все даги сделаны с помощью DockerOperator
5) Протестируйте ваши даги (5 баллов) https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html  - сделано через pytest
6) В docker compose так же настройте поднятие mlflow и запишите туда параметры обучения, метрики и артефакт(модель) (5 доп баллов) - сгорел, забил 
7) вместо пути в airflow variables  используйте апи Mlflow Model Registry (5 доп баллов) - сгорел, забил 
8) Настройте alert в случае падения дага (3 доп. балла) - настроено через google smtp
9) традиционно, самооценка (1 балл) - присутствует 

Итого: 5 + 10 + 5 + 3 + 10 + 5 + 3 + 1 = 42

2021-06-09 12:54 UTC, LenaSo requested changes
Пробрасывание volumes: путь на хосте ("/home/...") не настраивается, при этом указывается во всех DockerOperator-ax.

2021-06-09 12:54 UTC, LenaSo commented on airflow_ml_dags/dags/predict.py
> +        volumes=["/home/imd/Projects/made_ml_prod/airflow_ml_dags/data:/data"],
По заданию: "... в этом месте пробрасывается путь с хостовой машины, используйте здесь путь типа /tmp или считывайте из переменных окружения."

2021-06-09 13:23 UTC, IMDxD commented on airflow_ml_dags/dags/predict.py
> +        volumes=["/home/imd/Projects/made_ml_prod/airflow_ml_dags/data:/data"],
Поправил

2021-06-09 17:05 UTC, LenaSo commented
Good job! Согласна с самооценкой: 42 балла

2021-06-09 17:07 UTC, LenaSo approved these changes

2021-06-12 13:15 UTC, Mikhail-M commented on airflow_ml_dags/dags/predict.py
> +OUTPUT_DIR = Variable.get("OUTPUT_DIR")
https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#variables

2021-06-12 13:15 UTC, Mikhail-M approved these changes
Баллы: 42

2021-06-14 21:02 UTC, merged